version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    restart: always
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins

volumes:
  jenkins-data:
    external: true